[build]
  command = "yarn install --ignore-optional --prefer-offline && yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096"
  YARN_CACHE_FOLDER = "/opt/build/cache/yarn"
